# Build stage
FROM node:14-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN apk add --no-cache npm && \
    npm install && \
    npm prune --production

# Production stage
FROM node:14-alpine
WORKDIR /app
COPY . /app/.
COPY package*.json ./
RUN npm install --production
ENV PORT=8100
EXPOSE 8100
CMD [ "npm", "start" ]
